/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framecalculadora;

/**
 *
 * @author 0040481422033
 */
public class main extends javax.swing.JFrame {
    
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        lbl_Resultado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_PrimeiraVariavel = new javax.swing.JLabel();
        txt_PrimeiraVariavel = new javax.swing.JTextField();
        lbl_SegundaVariavel = new javax.swing.JLabel();
        txt_SegundaVariavel = new javax.swing.JTextField();
        btn_Soma = new javax.swing.JButton();
        btn_Subtracao = new javax.swing.JButton();
        btn_Multiplicacao = new javax.swing.JButton();
        btn_Divisao = new javax.swing.JButton();
        lbl_Texto = new javax.swing.JLabel();
        lbl_Resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbl_PrimeiraVariavel.setText("Primeira Variável");

        lbl_SegundaVariavel.setText("Segunda Variável");

        btn_Soma.setText("Soma");
        btn_Soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SomaActionPerformed(evt);
            }
        });

        btn_Subtracao.setText("Subtração");
        btn_Subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubtracaoActionPerformed(evt);
            }
        });

        btn_Multiplicacao.setText("Multiplicação");
        btn_Multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MultiplicacaoActionPerformed(evt);
            }
        });

        btn_Divisao.setText("Divisão");
        btn_Divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DivisaoActionPerformed(evt);
            }
        });

        lbl_Texto.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        lbl_Texto.setText("Resultado:");

        lbl_Resultado.setFont(new java.awt.Font("Times New Roman", 2, 48)); // NOI18N
        lbl_Resultado.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_Resultado))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_Multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                            .addComponent(btn_Divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lbl_PrimeiraVariavel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_PrimeiraVariavel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_SegundaVariavel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_SegundaVariavel, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Soma, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btn_Subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_Texto))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_PrimeiraVariavel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_PrimeiraVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_SegundaVariavel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_SegundaVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Soma)
                    .addComponent(btn_Subtracao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Multiplicacao)
                    .addComponent(btn_Divisao))
                .addGap(18, 18, 18)
                .addComponent(lbl_Texto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Resultado)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        lbl_Texto.getAccessibleContext().setAccessibleName("lbl_Resultado");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MultiplicacaoActionPerformed
        // TODO add your handling code here:
        
        Calculadora calc = new Calculadora( Double.parseDouble(txt_PrimeiraVariavel.getText()), Double.parseDouble(txt_SegundaVariavel.getText()), '*');
        
        lbl_Resultado.setText(Double.toString(calc.CalculandoOperacoes()));
        
        lbl_Resultado.setVisible(true);
    }//GEN-LAST:event_btn_MultiplicacaoActionPerformed

    private void btn_DivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DivisaoActionPerformed
        // TODO add your handling code here:
        Calculadora calc = new Calculadora( Double.parseDouble(txt_PrimeiraVariavel.getText()), Double.parseDouble(txt_SegundaVariavel.getText()), '/');
        
        lbl_Resultado.setText(Double.toString(calc.CalculandoOperacoes()));
        
        lbl_Resultado.setVisible(true);
    }//GEN-LAST:event_btn_DivisaoActionPerformed

    private void btn_SomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SomaActionPerformed
        // TODO add your handling code here:
        Calculadora calc = new Calculadora( Double.parseDouble(txt_PrimeiraVariavel.getText()), Double.parseDouble(txt_SegundaVariavel.getText()), '+');
        
        lbl_Resultado.setText(Double.toString(calc.CalculandoOperacoes()));
        
        lbl_Resultado.setVisible(true);
    }//GEN-LAST:event_btn_SomaActionPerformed

    private void btn_SubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubtracaoActionPerformed
        // TODO add your handling code here:
        Calculadora calc = new Calculadora( Double.parseDouble(txt_PrimeiraVariavel.getText()), Double.parseDouble(txt_SegundaVariavel.getText()), '-');
        
        lbl_Resultado.setText(Double.toString(calc.CalculandoOperacoes()));
        
        lbl_Resultado.setVisible(true);
    }//GEN-LAST:event_btn_SubtracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Divisao;
    private javax.swing.JButton btn_Multiplicacao;
    private javax.swing.JButton btn_Soma;
    private javax.swing.JButton btn_Subtracao;
    private javax.swing.JLabel lbl_PrimeiraVariavel;
    private javax.swing.JLabel lbl_Resultado;
    private javax.swing.JLabel lbl_SegundaVariavel;
    private javax.swing.JLabel lbl_Texto;
    private javax.swing.JTextField txt_PrimeiraVariavel;
    private javax.swing.JTextField txt_SegundaVariavel;
    // End of variables declaration//GEN-END:variables
}
